### ISSUE TITLE
consider removing package-lock.json

### ISSUE THREAD

**Issue by kessler** [yuraxdrumz/Bliz#4]
Just a suggestion, take a look at: https://github.com/npm/npm/issues/20603

tldr:

> Committing package-lock.json to the source code version control means that the project maintainers and CI systems will use a specific version of dependencies that may or may not match those defined in package.json. Because package-lock.json cannot be added to NPM registry (by design; see NPM shrinkwrap), projects that depend on a project that uses package-lock.json will themselves use package.json to resolve project's dependencies, i.e. what works for project maintainers/ CI systems might not work when the project is used as a dependency.

**Comment by yuraxdrumz** [comment]
Thanks, did not notice. I will remove it.
